### ISSUE TITLE
请问这是苹果用户才能用吗？

### ISSUE THREAD

**Issue by demolanguage** [torta/dark-dmzj#1]

**Comment by torta** [comment]
安卓的 2.7 版本 app 有 bug, 换 2.5 版本可以用.

[https://api.dmzj.com/download/dmzj.apk](https://api.dmzj.com/download/dmzj.apk)

**Comment by demolanguage** [comment]
@torta 感谢，很棒的项目

**Comment by demolanguage** [comment]
@torta 动漫之家2.7版本的使用
dmzj://dmzj.com/comic?id=<ID>
就能打开了😌能更新一下吗
